terminate called after throwing an instance of 'std::invalid_argument'
  what():  stod
timeout: the monitored command dumped core
